# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb1f93dc6e321ccc78dd788675bb8b0bb1bddbb0376ad238ebfa3e3ee33ec523182a43cbb1845549365c5060478db97b9f34d9d6eb7b163bb355866c2e6c832

test:
  secret_key_base: bbcb3af1c67ef99066a66c6273f0bc37b28eab719e491ba6c941410dedae948fa7c1f525bfd1d65b55b928ef6dcdfaa85ed5da078ffbfa194a5587d7b73876cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
